/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_malwarefight_methodhash_MethodSum */

#ifndef _Included_gq_malwarefight_methodhash_MethodSum
#define _Included_gq_malwarefight_methodhash_MethodSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_malwarefight_methodhash_MethodSum
 * Method:    unsignedLongDivision
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_gq_malwarefight_methodhash_MethodSum_unsignedLongMod
        (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
